package tiketbioskop;

public class FrameTiketBioskop extends javax.swing.JFrame {

    public FrameTiketBioskop() {
        initComponents();
        btn_film_one.setText(TiketBioskop.filmList.get(0).getName().toUpperCase());
        btn_film_two.setText(TiketBioskop.filmList.get(1).getName().toUpperCase());
        btn_film_three.setText(TiketBioskop.filmList.get(2).getName().toUpperCase());
        btn_film_four.setText(TiketBioskop.filmList.get(3).getName().toUpperCase());
        btn_film_five.setText(TiketBioskop.filmList.get(4).getName().toUpperCase());
        btn_film_six.setText(TiketBioskop.filmList.get(5).getName().toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_film_one = new javax.swing.JButton();
        btnf_close = new javax.swing.JButton();
        btn_film_two = new javax.swing.JButton();
        btn_film_three = new javax.swing.JButton();
        btn_film_five = new javax.swing.JButton();
        btn_film_six = new javax.swing.JButton();
        btn_film_four = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PILIH FILM");

        btn_film_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_film_oneActionPerformed(evt);
            }
        });

        btnf_close.setText("Batal");
        btnf_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf_closeActionPerformed(evt);
            }
        });

        btn_film_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_film_twoActionPerformed(evt);
            }
        });

        btn_film_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_film_threeActionPerformed(evt);
            }
        });

        btn_film_five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_film_fiveActionPerformed(evt);
            }
        });

        btn_film_six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_film_sixActionPerformed(evt);
            }
        });

        btn_film_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_film_fourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnf_close, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_film_one, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_film_four, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(64, 64, 64)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_film_two, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_film_five, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(66, 66, 66)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_film_three, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_film_six, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_film_two, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btn_film_three, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_film_one, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_film_four, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btn_film_five, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_film_six, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(btnf_close)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnf_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf_closeActionPerformed
        this.setVisible(false);
        new MenuUtama().setVisible(true);
    }//GEN-LAST:event_btnf_closeActionPerformed

    private void btn_film_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_film_fourActionPerformed
        this.pilihJam(3);
    }//GEN-LAST:event_btn_film_fourActionPerformed

    private void btn_film_sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_film_sixActionPerformed
        this.pilihJam(5);
    }//GEN-LAST:event_btn_film_sixActionPerformed

    private void btn_film_fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_film_fiveActionPerformed
        this.pilihJam(4);
    }//GEN-LAST:event_btn_film_fiveActionPerformed

    private void btn_film_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_film_threeActionPerformed
        this.pilihJam(2);
    }//GEN-LAST:event_btn_film_threeActionPerformed

    private void btn_film_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_film_twoActionPerformed
        this.pilihJam(1);
    }//GEN-LAST:event_btn_film_twoActionPerformed

    private void btn_film_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_film_oneActionPerformed
        this.pilihJam(0);
    }//GEN-LAST:event_btn_film_oneActionPerformed

    public void pilihJam(int filmidx) {
        new PilihJam(filmidx).setVisible(true);
        this.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTiketBioskop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_film_five;
    private javax.swing.JButton btn_film_four;
    private javax.swing.JButton btn_film_one;
    private javax.swing.JButton btn_film_six;
    private javax.swing.JButton btn_film_three;
    private javax.swing.JButton btn_film_two;
    private javax.swing.JButton btnf_close;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
